# Generated by Django 4.0 on 2021-12-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='tone',
            field=models.CharField(default='no tone', max_length=64),
            preserve_default=False,
        ),
    ]
