# Generated by Django 4.0 on 2021-12-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_remove_song_artist_song_tone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('name', 'user_id')},
        ),
    ]
